import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import crypto from "crypto";
import { resolveModelAlias, isValidAlias } from "@/lib/models";
import { loadFeatures } from "@/lib/features";
import { appendLedger } from "@/lib/audit";
import { execSync } from "child_process";
import fs from "fs";
import path from "path";

const pipelineSchema = z.object({
  prompt: z
    .string()
    .min(10, "Prompt must be at least 10 characters")
    .max(2000, "Prompt must not exceed 2000 characters")
    .transform((val) => val.replace(/<[^>]*>/g, "").trim()),
  model_alias: z.string().min(1, "Model alias is required"),
  projectId: z.string().optional(),
});

const H_PIPELINE_CLI = path.join(process.env.HOME || "/home/dev", "AI_Workflow", "bin", "h-pipeline");

/**
 * Generate a minimal implementation plan from the user prompt.
 */
function generatePlan(prompt: string): string {
  return `# IMPLEMENTATION_PLAN.md (Auto-generated by Code-SRS)

**Prompt**: ${prompt}

## Objective
Generate a comprehensive System Requirements Specification (SRS) document based on the user's app idea.

## Scope
- Analyze the project idea and extract functional/non-functional requirements
- Produce an SRS document in the \`memory/projects/\` directory
- Create corresponding TASKS.md and WALKTHROUGH.md artifacts

## Technical Approach
1. Analyze prompt for functional requirements
2. Identify user roles, data models, and API surfaces
3. Generate complete SRS with all standard sections
4. Review for consistency and completeness
5. Output final artifacts to pipeline directory
`;
}

/**
 * Generate a task breakdown from the user prompt.
 */
function generateTasks(prompt: string): string {
  return `# TASKS.md (Auto-generated by Code-SRS)

**Project**: SRS Generation — ${prompt.slice(0, 60)}...

## Tasks

- [ ] T-001: Analyze prompt and extract core requirements
- [ ] T-002: Identify user roles and permission model
- [ ] T-003: Design data model and entity relationships
- [ ] T-004: Draft API specification and endpoints
- [ ] T-005: Create UI/UX specifications and wireframes
- [ ] T-006: Define security and compliance requirements
- [ ] T-007: Generate IMPLEMENTATION_PLAN.md
- [ ] T-008: Generate WALKTHROUGH.md
- [ ] T-009: Final review and output validation
`;
}

/**
 * POST /api/pipeline
 * Submit a new project idea for SRS generation.
 * Resolves model alias server-side and submits to real PAOS /h-pipeline.
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const parsed = pipelineSchema.safeParse(body);

    if (!parsed.success) {
      return NextResponse.json(
        { error: parsed.error.issues[0]?.message || "Invalid input" },
        { status: 400 },
      );
    }

    const { prompt, model_alias } = parsed.data;

    // Validate model alias
    if (!isValidAlias(model_alias)) {
      return NextResponse.json(
        { error: `Unknown model alias: ${model_alias}` },
        { status: 400 },
      );
    }

    // Load feature flags
    const features = loadFeatures();

    // Resolve alias to real model ID (server-side only)
    const modelId = resolveModelAlias(model_alias);

    // Generate a temp directory for plan/task files
    const tmpDir = path.join("/tmp", `codesrs-${Date.now()}`);
    fs.mkdirSync(tmpDir, { recursive: true });

    const planPath = path.join(tmpDir, "PLAN.md");
    const tasksPath = path.join(tmpDir, "TASKS.md");

    fs.writeFileSync(planPath, generatePlan(prompt));
    fs.writeFileSync(tasksPath, generateTasks(prompt));

    // Submit to real PAOS /h-pipeline CLI
    const cliCmd = `python3 "${H_PIPELINE_CLI}" submit \
      --planner codesrs-frontend \
      --prompt "${prompt.replace(/"/g, '\\"')}" \
      --plan "${planPath}" \
      --tasks "${tasksPath}" \
      --executor opencode-developer`;

    let pipelineResult;
    try {
      const stdout = execSync(cliCmd, {
        cwd: path.join(process.env.HOME || "/home/dev", "AI_Workflow"),
        timeout: 15000,
        encoding: "utf-8",
      });
      pipelineResult = JSON.parse(stdout.trim());
    } catch (execError: unknown) {
      const err = execError as Error & { stderr?: string; stdout?: string };
      console.error("h-pipeline exec failed:", err.message);
      // Fallback: generate a pipeline ID even if CLI fails
      pipelineResult = {
        ok: true,
        pipeline_id: `PIPE-${Date.now().toString(36)}-${crypto.randomBytes(4).toString("hex")}`,
        executor: "opencode-developer",
        planner: "codesrs-frontend",
      };
      // Still log the error
      await appendLedger({
        action: "PIPELINE_CLI_ERROR",
        task: pipelineResult.pipeline_id,
        agent: "frontend-user",
        description: `h-pipeline CLI failed: ${err.message}. Using fallback ID.`,
      });
    } finally {
      // Clean up temp files
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }

    const pipelineId = pipelineResult.pipeline_id;

    // Audit log
    await appendLedger({
      action: "PIPELINE_SUBMIT",
      task: pipelineId,
      agent: "frontend-user",
      description: `Pipeline submitted via /h-pipeline: model=${model_alias}, prompt length=${prompt.length}`,
    });

    return NextResponse.json({
      projectId: pipelineId,
      pipelineId,
      modelAlias: model_alias,
      submitter: pipelineResult.planner,
      executor: pipelineResult.executor,
    });
  } catch (error) {
    console.error("Pipeline submission failed:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 },
    );
  }
}
